Pim\Bundle\MagentoConnectorBundle\Entity\DeltaConfigurableExport:
    type: entity
    table: pim_magento_delta_configurable_export
    indexes:
        searchcode_idx:
            columns:
                - id
    uniqueConstraints:
        searchunique_idx:
            columns:
                - id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        lastExport:
            type: datetime
            column: last_export
        productId:
            type: string
            column: product_id
    manyToOne:
        jobInstance:
            targetEntity: Akeneo\Bundle\BatchBundle\Entity\JobInstance
            joinColumns:
                job_instance_id:
                    referencedColumnName: id
                    onDelete: CASCADE
