connector:
    name: Magento Connector Bundle
    jobs:
        magento_product_export:
            title: pim_magento_connector.jobs.magento_product_export.title
            type:  export
            steps:
                export:
                    title: pim_magento_connector.jobs.magento_product_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_magento_connector.processor.simple_product_to_array
                        writer:    pim_magento_connector.writer.api_import
