connector:
    name: Magento Connector Bundle
    jobs:
        magento_product_export:
            title: pim_magento_connector.jobs.magento_product_export.title
            type:  export
            steps:
                export_product:
                    title: pim_magento_connector.jobs.magento_product_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_magento_connector.processor.product_to_array
                        writer:    pim_magento_connector.writer.product
                update_product_associations:
                    title: pim_magento_connector.jobs.magento_product_associations_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.product_association
                        processor: pim_magento_connector.processor.associated_product_to_array
                        writer:    pim_base_connector.writer.dummy

        magento_attribute_export:
            title: pim_magento_connector.jobs.magento_attribute_export.title
            type:  export
            steps:
                export_product:
                    title: pim_magento_connector.jobs.magento_attribute_export.export.title
                    services:
                        reader:    pim_base_connector.reader.orm.attribute
                        processor: pim_magento_connector.processor.attribute
                        writer:    pim_base_connector.writer.dummy

        magento_configurable_export:
            title: pim_magento_connector.jobs.magento_configurable_export.title
            type:  export
            steps:
                export:
                    title: pim_magento_connector.jobs.magento_configurable_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.variant_group
                        processor: pim_magento_connector.processor.variant_group_to_array
                        writer:    pim_base_connector.writer.dummy
