connector:
    name: Magento Connector Bundle
    jobs:
        magento_product_export:
            title: pim_magento_connector.jobs.magento_product_export.title
            type:  export
            steps:
                export_product:
                    title: pim_magento_connector.jobs.magento_product_export.export.title
                    services:
                        reader:    pim_base_connector.reader.doctrine.product
                        processor: pim_magento_connector.processor.product_to_array
                        writer:    pim_magento_connector.writer.product
                update_product_associations:
                    title: pim_magento_connector.jobs.magento_product_associations_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.product_association
                        processor: pim_magento_connector.processor.associated_product_to_array
                        writer:    pim_base_connector.writer.dummy

        magento_category_export:
            title: pim_magento_connector.jobs.magento_category_export.title
            type:  export
            steps:
                export_product:
                    title: pim_magento_connector.jobs.magento_category_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.category
                        processor: pim_magento_connector.processor.category
                        writer:    pim_base_connector.writer.dummy

        magento_attribute_export:
            title: pim_magento_connector.jobs.magento_attribute_export.title
            type:  export
            steps:
                export_family:
                    title: pim_magento_connector.jobs.magento_family_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.family
                        processor: pim_magento_connector.processor.family
                        writer:    pim_magento_connector.writer.family
                export_attribute:
                    title: pim_magento_connector.jobs.magento_attribute_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.attribute
                        processor: pim_magento_connector.processor.attribute
                        writer:    pim_magento_connector.writer.attribute
                export_association:
                    title: pim_magento_connector.jobs.magento_association_attribute_to_sets_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.attribute
                        processor: pim_magento_connector.processor.add_attribute_to_sets
                        writer:    pim_magento_connector.writer.add_attribute_to_sets

        magento_configurable_export:
            title: pim_magento_connector.jobs.magento_configurable_export.title
            type:  export
            steps:
                export:
                    title: pim_magento_connector.jobs.magento_configurable_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.variant_group
                        processor: pim_magento_connector.processor.variant_group_to_array
                        writer:    pim_base_connector.writer.dummy
