parameters:
    pim_magento_connector.factory.magento_soap_client.class: Pim\Bundle\MagentoConnectorBundle\Factory\MagentoSoapClientFactory

services:
    pim_magento_connector.factory.magento_soap_client:
        class: %pim_magento_connector.factory.magento_soap_client.class%
        arguments:
            - %pim_magento_connector.webservice.magento_soap_client.class%
