parameters:
    pim_magento_connector.guesser.magento_webservice.class: Pim\Bundle\MagentoConnectorBundle\Guesser\WebserviceGuesser
    pim_magento_connector.guesser.magento_normalizer.class: Pim\Bundle\MagentoConnectorBundle\Guesser\NormalizerGuesser

services:
    pim_magento_connector.guesser.magento_webservice:
        class: %pim_magento_connector.guesser.magento_webservice.class%
        arguments:
            - '@pim_magento_connector.factory.magento_soap_client'

    pim_magento_connector.guesser.magento_normalizer:
        class: %pim_magento_connector.guesser.magento_normalizer.class%
        arguments:
            - '@pim_magento_connector.factory.magento_soap_client'
            - '@pim_magento_connector.normalizer.registry'
