parameters:
    pim_magento_connector.helper.price.class: Pim\Bundle\MagentoConnectorBundle\Helper\PriceHelper
    pim_magento_connector.helper.magento_attributes.class: Pim\Bundle\MagentoConnectorBundle\Helper\MagentoAttributesHelper

services:
    pim_magento_connector.helper.price:
        class: %pim_magento_connector.helper.price.class%

    pim_magento_connector.helper.magento_attributes:
        class: %pim_magento_connector.helper.magento_attributes.class%
