parameters:
    pim_magento_connector.normalizer.value.class:  Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductValueNormalizer
    pim_magento_connector.normalizer.attribute.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\AttributeNormalizer
    pim_magento_connector.normalizer.category.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\CategoryNormalizer
    pim_magento_connector.normalizer.family.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\FamilyNormalizer
    pim_magento_connector.normalizer.option.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\OptionNormalizer
    pim_magento_connector.normalizer.product.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductNormalizer
    pim_magento_connector.normalizer.product16.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductNormalizer16
    pim_magento_connector.normalizer.configurable.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ConfigurableNormalizer
    pim_magento_connector.normalizer.registry.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\NormalizerRegistry

services:
    pim_magento_connector.normalizer.value:
        class: %pim_magento_connector.normalizer.value.class%

    pim_magento_connector.normalizer.attribute:
        class: %pim_magento_connector.normalizer.attribute.class%
        arguments:
            - '@pim_magento_connector.normalizer.value'
        tags:
            - { name: magento_normalizer, normalizer_key: 'attribute' }

    pim_magento_connector.normalizer.category:
        class: %pim_magento_connector.normalizer.category.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.manager.category_mapping'
            - '@pim_magento_connector.repository.category'
        tags:
            - { name: magento_normalizer, normalizer_key: 'category' }

    pim_magento_connector.normalizer.family:
        class: %pim_magento_connector.normalizer.family.class%
        tags:
            - { name: magento_normalizer, normalizer_key: 'family' }

    pim_magento_connector.normalizer.option:
        class: %pim_magento_connector.normalizer.option.class%
        arguments:
            - '@pim_catalog.manager.channel'
        tags:
            - { name: magento_normalizer, normalizer_key: 'option' }

    pim_magento_connector.normalizer.product:
        class: %pim_magento_connector.normalizer.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.media'
            - '@pim_magento_connector.normalizer.value'
            - '@pim_magento_connector.manager.category_mapping'
            - '@pim_magento_connector.manager.association_type'
            - '@pim_magento_connector.filters.exportable_locale'
        tags:
            - { name: magento_normalizer, normalizer_key: 'product' }

    pim_magento_connector.normalizer.product16:
        class: %pim_magento_connector.normalizer.product16.class%
        parent: pim_magento_connector.normalizer.product
        tags:
            - { name: magento_normalizer, normalizer_key: 'product16' }

    pim_magento_connector.normalizer.configurable:
        class: %pim_magento_connector.normalizer.configurable.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.normalizer.product'
        tags:
            - { name: magento_normalizer, normalizer_key: 'configurable' }


    pim_magento_connector.normalizer.registry:
        class: %pim_magento_connector.normalizer.registry.class%
