parameters:
    pim_magento_connector.processor.simple_product_to_array.class:   Pim\Bundle\MagentoConnectorBundle\Processor\SimpleProductToArrayProcessor

services:
    pim_magento_connector.processor.simple_product_to_array:
        class: %pim_magento_connector.processor.simple_product_to_array.class%
        arguments:
          - @pim_magento_connector.serializer
