parameters:
    pim_magento_connector.purger.mapping.class: Pim\Bundle\MagentoConnectorBundle\Purger\MappingPurger

services:
    pim_magento_connector.purger.mapping:
        class: %pim_magento_connector.purger.mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_import_export.repository.job_instance'
        calls:
            - [setMappingClasses, [{%pim_magento_connector.entity.category_mapping.class%, %pim_magento_connector.entity.family_mapping.class%, %pim_magento_connector.entity.group_mapping.class%, %pim_magento_connector.entity.attribute_mapping.class%}]]
