parameters:
    pim_magento_connector.reader.variant_group.class: Pim\Bundle\MagentoConnectorBundle\Reader\VariantGroupReader
    pim_magento_connector.reader.attribute.class: Pim\Bundle\MagentoConnectorBundle\Reader\AttributeReader
    pim_magento_connector.reader.family.class: Pim\Bundle\MagentoConnectorBundle\Reader\FamilyReader
    pim_magento_connector.reader.product_association.class: Pim\Bundle\MagentoConnectorBundle\Reader\ProductAssociationReader
    pim_magento_connector.reader.category.class: Pim\Bundle\MagentoConnectorBundle\Reader\CategoryReader

services:
    pim_magento_connector.reader.variant_group:
        class: %pim_magento_connector.reader.variant_group.class%
        arguments:
            - '@pim_base_connector.reader.doctrine.product'

    pim_magento_connector.reader.attribute:
        class: %pim_magento_connector.reader.attribute.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.attribute.class%

    pim_magento_connector.reader.family:
        class: %pim_magento_connector.reader.family.class%
        arguments:
            - '@pim_catalog.repository.family'

    pim_magento_connector.reader.product_association:
        class: %pim_magento_connector.reader.product_association.class%
        arguments:
            - '@pim_base_connector.reader.doctrine.product'

    pim_magento_connector.reader.category:
        class: %pim_magento_connector.reader.category.class%
        arguments:
            - '@pim_catalog.repository.category'
            - '@pim_catalog.manager.channel'
