parameters:
    pim_magento_connector.reader.variant_group.class: Pim\Bundle\MagentoConnectorBundle\Reader\VariantGroupReader
    pim_magento_connector.reader.product_association.class: Pim\Bundle\MagentoConnectorBundle\Reader\ProductAssociationReader

services:
    pim_magento_connector.reader.variant_group:
        class: %pim_magento_connector.reader.variant_group.class%
        arguments:
            - '@pim_base_connector.reader.doctrine.product'

    pim_magento_connector.reader.product_association:
        class: %pim_magento_connector.reader.product_association.class%
        arguments:
            - '@pim_base_connector.reader.doctrine.product'
