parameters:
    pim_magento_connector.reader.variant_group.class: Pim\Bundle\MagentoConnectorBundle\Reader\VariantGroupReader

services:
    pim_magento_connector.reader.variant_group:
        class: %pim_magento_connector.reader.variant_group.class%
        arguments:
            - '@pim_catalog.manager.group'
