parameters:
    pim_magento_connector.repository.category.class:                         Pim\Bundle\MagentoConnectorBundle\Entity\Repository\CategoryRepository
    pim_magento_connector.repository.currency.class:                         Pim\Bundle\MagentoConnectorBundle\Entity\Repository\CurrencyRepository
    pim_magento_connector.repository.group.class:                            Pim\Bundle\MagentoConnectorBundle\Entity\Repository\GroupRepository
    pim_magento_connector.repository.delta_product_export.class:             Doctrine\ORM\EntityRepository
    pim_magento_connector.repository.delta_product_association_export.class: Doctrine\ORM\EntityRepository

services:
    pim_magento_connector.repository.category:
        class: %pim_magento_connector.repository.category.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_magento_connector.metadata.category'

    pim_magento_connector.repository.delta_product_export:
        class: %pim_magento_connector.repository.delta_product_export.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_magento_connector.entity.delta_product_export.class%]
        tags:
            - { name: 'pim_repository' }

    pim_magento_connector.repository.delta_product_association_export:
        class: %pim_magento_connector.repository.delta_product_association_export.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_magento_connector.entity.delta_product_association_export.class%]
        tags:
            - { name: 'pim_repository' }

    pim_magento_connector.repository.group:
        class: %pim_magento_connector.repository.group.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_magento_connector.metadata.group'

    pim_magento_connector.metadata.category:
        public: false
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments:
            name: %pim_catalog.entity.category.class%

    pim_magento_connector.metadata.currency:
        public: false
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments:
            name: %pim_catalog.entity.currency.class%

    pim_magento_connector.metadata.group:
        public: false
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments:
            name: %pim_catalog.entity.group.class%
