parameters:
    pim_magento_connector.normalizer.product.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductNormalizer
    pim_magento_connector.normalizer.product_value.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductValueNormalizer
    pim_magento_connector.normalizer.product_price.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductPriceNormalizer
    pim_magento_connector.normalizer.attribute_option.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\AttributeOptionNormalizer
    pim_magento_connector.normalizer.metric.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\MetricNormalizer
    pim_magento_connector.normalizer.datetime.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\DateTimeNormalizer
    pim_magento_connector.normalizer.collection.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\CollectionNormalizer
    pim_magento_connector.normalizer.product_category.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductCategoryNormalizer
    pim_magento_connector.normalizer.product_media.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductMediaNormalizer
    pim_magento_connector.normalizer.variant_group_helper.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\VariantGroupHelper
    pim_magento_connector.normalizer.group.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\GroupNormalizer
    pim_magento_connector.normalizer.association.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\AssociationNormalizer

services:
   pim_magento_connector.serializer:
       class: %pim_serializer.class%

   pim_magento_connector.normalizer.product:
       class: %pim_magento_connector.normalizer.product.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.product_value:
       class: %pim_magento_connector.normalizer.product_value.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.product_category:
       class: %pim_magento_connector.normalizer.product_category.class%
       arguments:
          - '@pim_catalog.manager.category'
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.product_price:
       class: %pim_magento_connector.normalizer.product_price.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.attribute_option:
       class: %pim_magento_connector.normalizer.attribute_option.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.metric:
       class: %pim_magento_connector.normalizer.metric.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.datetime:
       class: %pim_magento_connector.normalizer.datetime.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.collection:
       class: %pim_magento_connector.normalizer.collection.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.product_media:
       class: %pim_magento_connector.normalizer.product_media.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.group:
       class: %pim_magento_connector.normalizer.group.class%
       arguments:
          - '@pim_magento_connector.normalizer.variant_group_helper'
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }

   pim_magento_connector.normalizer.variant_group_helper:
       class: %pim_magento_connector.normalizer.variant_group_helper.class%
       arguments:
           - '@pim_magento_connector.helper.price'

   pim_magento_connector.normalizer.association:
       class: %pim_magento_connector.normalizer.association.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 100 }
