parameters:
    pim_magento_connector.normalizer.product.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductNormalizer
    pim_magento_connector.normalizer.product_value.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductValueNormalizer
    pim_magento_connector.normalizer.identifier.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\IdentifierNormalizer
    pim_magento_connector.normalizer.product_price.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductPriceNormalizer
    pim_magento_connector.normalizer.attribute_option.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\AttributeOptionNormalizer
    pim_magento_connector.normalizer.metric.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\MetricNormalizer
    pim_magento_connector.normalizer.generic.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\GenericNormalizer
    pim_magento_connector.normalizer.datetime.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\DateTimeNormalizer

services:
   pim_magento_connector.serializer:
       class: %pim_serializer.class%

   pim_magento_connector.normalizer.product:
       class: %pim_magento_connector.normalizer.product.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 90 }
   pim_magento_connector.normalizer.product_value:
       class: %pim_magento_connector.normalizer.product_value.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 90 }
   pim_magento_connector.normalizer.product_price:
       class: %pim_magento_connector.normalizer.product_price.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 90 }
   pim_magento_connector.normalizer.attribute_option:
       class: %pim_magento_connector.normalizer.attribute_option.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 90 }
   pim_magento_connector.normalizer.metric:
       class: %pim_magento_connector.normalizer.metric.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 90 }
   pim_magento_connector.datetime.metric:
       class: %pim_magento_connector.normalizer.datetime.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 90 }
   pim_magento_connector.normalizer.generic:
       class: %pim_magento_connector.normalizer.generic.class%
       tags:
          - { name: pim_magento_connector.serializer.normalizer, priority: 80 }
