parameters:
    pim_magento_connector.writer.api_import.class: Pim\Bundle\MagentoConnectorBundle\Writer\ProductApiImportWriter

services:
    pim_magento_connector.writer.api_import:
        class: %pim_magento_connector.writer.api_import.class%
