parameters:
    pim_magento_connector.writer.product.class: Pim\Bundle\MagentoConnectorBundle\Writer\ProductWriter
    pim_magento_connector.writer.attribute.class: Pim\Bundle\MagentoConnectorBundle\Writer\AttributeWriter
    pim_magento_connector.writer.family.class: Pim\Bundle\MagentoConnectorBundle\Writer\FamilyWriter
    pim_magento_connector.writer.abstract.class: Pim\Bundle\MagentoConnectorBundle\Writer\AbstractWriter
    pim_magento_connector.writer.add_attribute_to_sets.class: Pim\Bundle\MagentoConnectorBundle\Writer\AddAttributeToSetsWriter

services:
    pim_magento_connector.writer.product:
        class: %pim_magento_connector.writer.product.class%
        parent: pim_magento_connector.writer.abstract

    pim_magento_connector.writer.attribute:
        class: %pim_magento_connector.writer.attribute.class%
        parent: pim_magento_connector.writer.abstract

    pim_magento_connector.writer.family:
        class: %pim_magento_connector.writer.family.class%
        parent: pim_magento_connector.writer.abstract

    pim_magento_connector.writer.add_attribute_to_sets:
        class: %pim_magento_connector.writer.add_attribute_to_sets.class%
        parent: pim_magento_connector.writer.abstract

    pim_magento_connector.writer.abstract:
        class: '%pim_magento_connector.writer.abstract.class%'
        abstract: true
        arguments:
            - '@pim_magento_connector.manager.magento_configuration'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]
