language: php
php:
    - "5.5"
    - "5.4"
    - "hhvm"

before_script:
    - composer self-update --no-interaction
    - composer update --prefer-dist --no-scripts --no-interaction

script: bin/phpspec run -fpretty -v

matrix:
  allow_failures:
      - php: hhvm
