parameters:
    pim_magento_connector.reader.delta_product.class:             Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaProductReader
    pim_magento_connector.reader.delta_product_association.class: Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaProductAssociationReader
    pim_magento_connector.reader.delta_configurable.class:        Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaConfigurableReader
