parameters:
    pim_magento_connector.reader.delta_product.class:             Pim\Bundle\MagentoConnectorBundle\Reader\ORM\DeltaProductReader
    pim_magento_connector.reader.delta_product_association.class: Pim\Bundle\MagentoConnectorBundle\Reader\ORM\DeltaProductAssociationReader
    pim_magento_connector.reader.delta_configurable.class:        Pim\Bundle\MagentoConnectorBundle\Reader\ORM\DeltaConfigurableReader

services:
    pim_magento_connector.reader.product_delta:
        class: %pim_magento_connector.reader.delta_product.class%
        parent: pim_base_connector.reader.doctrine.product

    pim_magento_connector.reader.delta_product_association:
        class: %pim_magento_connector.reader.delta_product_association.class%
        parent: pim_base_connector.reader.doctrine.product

    pim_magento_connector.reader.delta_configurable:
        class: %pim_magento_connector.reader.delta_configurable.class%
        parent: pim_base_connector.reader.doctrine.product
