parameters:
    pim_magento_connector.reader.delta_product.class:             Pim\Bundle\MagentoConnectorBundle\Reader\ORM\DeltaProductReader
    pim_magento_connector.reader.delta_product_association.class: Pim\Bundle\MagentoConnectorBundle\Reader\ORM\DeltaProductAssociationReader
    pim_magento_connector.reader.delta_configurable.class:        Pim\Bundle\MagentoConnectorBundle\Reader\ORM\DeltaConfigurableReader
